"""Fix department foreign key on Ticket, other relationship updates

Revision ID: 345d0d279800
Revises: f9968c20b028
Create Date: 2025-11-06 11:16:29.049513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345d0d279800'
down_revision = 'f9968c20b028'
branch_labels = None
depends_on = None


def upgrade():
    # In your Alembic migration file:
    with op.batch_alter_table('tickets') as batch_op:
       batch_op.drop_column('department')
       batch_op.add_column(sa.Column('department', sa.Integer(), sa.ForeignKey('departments.department_id')))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('department',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
