"""empty message

Revision ID: 96f7164a6f79
Revises: 30da6f241071
Create Date: 2025-11-23 18:07:06.513909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96f7164a6f79'
down_revision = '30da6f241071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archived_tickets',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('assignee', sa.Integer(), nullable=True),
    sa.Column('department', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignee'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['author'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['department'], ['departments.department_id'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archived_tickets')
    # ### end Alembic commands ###
