"""empty message

Revision ID: d9c6c1d3f3e4
Revises: 2d05c3caccf4
Create Date: 2025-11-26 11:52:58.201161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c6c1d3f3e4'
down_revision = '2d05c3caccf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('department_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('majors',
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.PrimaryKeyConstraint('major_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('minors',
    sa.Column('minor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.PrimaryKeyConstraint('minor_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('major_id', sa.Integer(), nullable=True),
    sa.Column('minor_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.ForeignKeyConstraint(['major_id'], ['majors.major_id'], ),
    sa.ForeignKeyConstraint(['minor_id'], ['minors.minor_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('archived_tickets',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('assignee', sa.Integer(), nullable=True),
    sa.Column('department', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignee'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['author'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['department'], ['departments.department_id'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_table('tickets',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('assignee', sa.Integer(), nullable=True),
    sa.Column('department', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignee'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['author'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['department'], ['departments.department_id'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_table('responses',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ticket', sa.Integer(), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['ticket'], ['tickets.ticket_id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responses')
    op.drop_table('tickets')
    op.drop_table('archived_tickets')
    op.drop_table('users')
    op.drop_table('minors')
    op.drop_table('majors')
    op.drop_table('departments')
    # ### end Alembic commands ###
