"""Add major_id, minor_id, department_id to users

Revision ID: f9968c20b028
Revises: 25e04cbcf726
Create Date: 2025-10-30 12:48:37.989764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9968c20b028'
down_revision = '25e04cbcf726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('department_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('majors',
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.PrimaryKeyConstraint('major_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('minors',
    sa.Column('minor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.PrimaryKeyConstraint('minor_id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('major_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('minor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'majors', ['major_id'], ['major_id'])
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['department_id'])
        batch_op.create_foreign_key(None, 'minors', ['minor_id'], ['minor_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('department_id')
        batch_op.drop_column('minor_id')
        batch_op.drop_column('major_id')

    op.drop_table('minors')
    op.drop_table('majors')
    op.drop_table('departments')
    # ### end Alembic commands ###
